In [1]:
import pickle
import numpy as np

import sys
sys.path.append('..')
import ctmc

## Load Demo Dataset
A preprocessed data list is used.

In [2]:
with open("../data/example.pkl", "rb") as f:
    datalist = pickle.load(f)
numstates = 9

# Fit with uncorrected data

In [3]:
model1 = ctmc.Ctmc(numstates, transintv=1.0, toltime=1e-8, debug=False)
model1 = model1.fit(datalist)
mat1 = model1.transmat
mat1.round(2)

array([[0.96, 0.04, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.04, 0.9 , 0.06, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.03, 0.89, 0.08, 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.06, 0.86, 0.06, 0.01, 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.11, 0.8 , 0.08, 0.  , 0.  , 0.01],
       [0.  , 0.  , 0.  , 0.01, 0.1 , 0.79, 0.05, 0.01, 0.04],
       [0.  , 0.  , 0.  , 0.  , 0.01, 0.21, 0.53, 0.17, 0.07],
       [0.  , 0.  , 0.  , 0.  , 0.03, 0.38, 0.06, 0.52, 0.01],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.03, 0.  , 0.  , 0.97]])

# Fit with auto-corrected data

In [4]:
model2 = ctmc.Ctmc(numstates, transintv=1.0, toltime=1e-8, autocorrect=True, debug=False)
model2 = model2.fit(datalist)
mat2 = model2.transmat
mat2.round(2)

array([[0.96, 0.04, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.04, 0.9 , 0.06, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.03, 0.89, 0.08, 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.06, 0.86, 0.06, 0.01, 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.11, 0.8 , 0.08, 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.01, 0.1 , 0.79, 0.05, 0.01, 0.04],
       [0.  , 0.  , 0.  , 0.  , 0.01, 0.21, 0.53, 0.17, 0.07],
       [0.  , 0.  , 0.  , 0.  , 0.03, 0.38, 0.06, 0.52, 0.01],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 1.  ]])

# Differences

In [5]:
(mat2 - mat1).round(2)

array([[ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , -0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , -0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , -0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , -0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , -0.  ],
       [-0.  , -0.  , -0.  , -0.  , -0.  , -0.  , -0.  , -0.  ,  0.  ],
       [-0.  , -0.  , -0.  , -0.  , -0.  , -0.  , -0.  , -0.  ,  0.  ],
       [-0.  , -0.  , -0.  , -0.  , -0.  , -0.  , -0.  , -0.  ,  0.  ],
       [-0.  , -0.  , -0.  , -0.  , -0.  , -0.03, -0.  , -0.  ,  0.03]])